### ISSUE TITLE
Should trailing separator be required?

### ISSUE THREAD

**Issue by romdotdog** [bottom-software-foundation/spec#4]
bottom-rs allows decoding without a trailing byte separator. bottom-lua requires trailing separators to be present. The PR in bottom-py would make trailing separators required. An error  saying the input doesn't have a trailing byte separator or no trailing byte separators being decodable should be consistent across repositories.

**Comment by Moire9** [comment]
The separator is now more accurately called a terminator as of #8, so you can probably close this PR (the answer being yes, it should be required)
